name: Deploy to HR Student Hosting

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v3

      - name: Upload files to HR hosting
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: stud.hosted.hr.nl
          port: 22
          username: 1053476
          password: ${{ secrets.FTP_PASS }}
          local_path: ./
          remote_path: public.www/